import pygame
WIDTH = 400
HEIGHT = 500
FPS = 30

INDENT = LEFT_INDENT = 20
UPPER_INDENT = 10

BUTTON_HEIGHT = 75
BUTTON_WIDTH = 165
BUTTON_BORDER = 6
BUTTON_HORIZONTAL_DIST = 30
BUTTON_VERTICAL_DIST = 25
BUTTON_TOP = 300
BUTTON_TITLE_HORIZONTAL = 40
BUTTON_TITLE_VERTICAL = 30

DEATH_INDENT_VERTICAL = 45

GOOSE_INDENT_VERTICAL = 90
GOOSE_INDENT_HORIZONTAL = 80
GOOSE_SIZE = 236

pygame.init()
pygame.mixer.init()
f = FONT = pygame.font.Font(None, 24)
